# ========================================================================
# Cloud Build Configuration for Firebase App Hosting
# ========================================================================
# 
# IMPORTANT: If you get "illegal base64 data" error:
# 1. The KMS secret must be base64-encoded before encryption
# 2. Or use cloudbuild-simple.yaml which uses Secret Manager (easier)
#
# To store secret in KMS correctly:
#   cat service-account.json | base64 -w 0 | gcloud kms encrypt ...
#
# ========================================================================

steps:
# -------------------------------------------------------------------------
# 1. Install pnpm (if not available in the image)
# -------------------------------------------------------------------------
- id: 'Install pnpm'
  name: 'node:20'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install -g pnpm@latest
      pnpm --version

# -------------------------------------------------------------------------
# 2. Get Service Account from Secret Manager
# -------------------------------------------------------------------------
- id: 'Get Service Account'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud secrets versions access latest --secret=firebaseServiceAccount --project=${_FIREBASE_PROJECT_ID} > /workspace/sa-key.json
      # Verify it's valid JSON
      if ! cat /workspace/sa-key.json | python3 -m json.tool > /dev/null 2>&1; then
        echo "ERROR: Service account is not valid JSON"
        cat /workspace/sa-key.json | head -c 200
        exit 1
      fi
      # Create base64 encoded version for environment variable (Next.js needs it as base64 string)
      cat /workspace/sa-key.json | base64 -w 0 > /workspace/firebase_sa_base64.txt
      echo "Service account retrieved and encoded"

# -------------------------------------------------------------------------
# 3. Install Dependencies
# -------------------------------------------------------------------------
- id: 'Install Dependencies'
  name: 'node:20'
  entrypoint: 'pnpm'
  args: ['install', '--frozen-lockfile']
  waitFor: ['Install pnpm']

# -------------------------------------------------------------------------
# 4. Build Next.js Application
#    - Includes all environment variables needed for build
#    - FIREBASE_SERVICE_ACCOUNT is available for server-side code
# -------------------------------------------------------------------------
- id: 'Build'
  name: 'node:20'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Read the base64 encoded service account
      FIREBASE_SERVICE_ACCOUNT_B64=$(cat /workspace/firebase_sa_base64.txt)
      
      # Build with all environment variables
      NEXT_PUBLIC_FIREBASE_API_KEY="${_FIREBASE_API_KEY}" \
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${_FIREBASE_AUTH_DOMAIN}" \
      NEXT_PUBLIC_FIREBASE_PROJECT_ID="${_FIREBASE_PROJECT_ID}" \
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${_FIREBASE_STORAGE_BUCKET}" \
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${_FIREBASE_MESSAGING_SENDER_ID}" \
      NEXT_PUBLIC_FIREBASE_APP_ID="${_FIREBASE_APP_ID}" \
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="${_FIREBASE_MEASUREMENT_ID}" \
      FIREBASE_SERVICE_ACCOUNT="${FIREBASE_SERVICE_ACCOUNT_B64}" \
      NODE_ENV=production \
      NEXT_PUBLIC_API_URL="${_API_URL:-https://videos--ghost-money-world.us-east4.hosted.app/api}" \
      pnpm run build
  waitFor: ['Install Dependencies', 'Get Service Account']

# -------------------------------------------------------------------------
# 5. Deploy to Firebase App Hosting
#    - Uses the decoded service account key file for authentication
# -------------------------------------------------------------------------
- id: 'Deploy'
  name: 'firebase/cli'
  args: 
    - 'deploy'
    - '--only'
    - 'apphosting'
    - '--project'
    - '${_FIREBASE_PROJECT_ID}'
  waitFor: ['Build']
  env:
    - 'FIREBASE_AUTH_EMULATOR_HOST=' # Clear potential emulator conflicts
    - 'GCLOUD_PROJECT=${_FIREBASE_PROJECT_ID}'
    - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/sa-key.json'

# -------------------------------------------------------------------------
# Substitutions - Set these in Cloud Build triggers or manually
# -------------------------------------------------------------------------
substitutions:
  # Firebase Client Configuration
  _FIREBASE_API_KEY: 'AIzaSyCSnOql-nQLIvbhWAhQZg_Sb6Kwu95i5ew'
  _FIREBASE_AUTH_DOMAIN: 'ghost-money-world.firebaseapp.com'
  _FIREBASE_PROJECT_ID: 'ghost-money-world'
  _FIREBASE_STORAGE_BUCKET: 'ghost-money-world.firebasestorage.app'
  _FIREBASE_MESSAGING_SENDER_ID: '276987047372'
  _FIREBASE_APP_ID: '1:276987047372:web:d0ccc8e3c58a2122de8169'
  _FIREBASE_MEASUREMENT_ID: 'G-FEY4FCPZ63'
  
  # Optional
  _API_URL: 'https://videos--ghost-money-world.us-east4.hosted.app/api'

# -------------------------------------------------------------------------
# Secrets Configuration
# -------------------------------------------------------------------------
# Using Secret Manager instead of KMS
# The secret 'firebaseServiceAccount' is retrieved in the 'Get Service Account' step
# Make sure the Cloud Build service account has 'Secret Manager Secret Accessor' role

# -------------------------------------------------------------------------
# Options
# -------------------------------------------------------------------------
options:
  machineType: 'E2_HIGHCPU_8'  # Use high CPU for faster builds
  logging: CLOUD_LOGGING_ONLY

# -------------------------------------------------------------------------
# Timeout
# -------------------------------------------------------------------------
timeout: '1200s'  # 20 minutes timeout
