steps:
# -------------------------------------------------------------------------
# 1. Install pnpm
# -------------------------------------------------------------------------
- id: 'Install pnpm'
  name: 'node:20'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install -g pnpm@latest
      pnpm --version

# -------------------------------------------------------------------------
# 2. Get Service Account from Secret Manager
#    This is simpler than KMS - just store your JSON file directly
# -------------------------------------------------------------------------
- id: 'Get Service Account'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Get the service account from Secret Manager
      gcloud secrets versions access latest --secret=firebase_sa_key --project=${_FIREBASE_PROJECT_ID} > /workspace/sa-key.json
      
      # Verify it's valid JSON
      if ! python3 -m json.tool /workspace/sa-key.json > /dev/null 2>&1; then
        echo "ERROR: Service account is not valid JSON"
        exit 1
      fi
      
      # Create base64 encoded version for Next.js environment variable
      cat /workspace/sa-key.json | base64 -w 0 > /workspace/firebase_sa_base64.txt
      echo "Service account retrieved successfully"

# -------------------------------------------------------------------------
# 3. Install Dependencies
# -------------------------------------------------------------------------
- id: 'Install Dependencies'
  name: 'node:20'
  entrypoint: 'pnpm'
  args: ['install', '--frozen-lockfile']
  waitFor: ['Install pnpm']

# -------------------------------------------------------------------------
# 4. Build Next.js Application
# -------------------------------------------------------------------------
- id: 'Build'
  name: 'node:20'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Read the base64 encoded service account
      FIREBASE_SERVICE_ACCOUNT_B64=$(cat /workspace/firebase_sa_base64.txt)
      
      # Build with all environment variables
      NEXT_PUBLIC_FIREBASE_API_KEY="${_FIREBASE_API_KEY}" \
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${_FIREBASE_AUTH_DOMAIN}" \
      NEXT_PUBLIC_FIREBASE_PROJECT_ID="${_FIREBASE_PROJECT_ID}" \
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${_FIREBASE_STORAGE_BUCKET}" \
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${_FIREBASE_MESSAGING_SENDER_ID}" \
      NEXT_PUBLIC_FIREBASE_APP_ID="${_FIREBASE_APP_ID}" \
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="${_FIREBASE_MEASUREMENT_ID}" \
      FIREBASE_SERVICE_ACCOUNT="${FIREBASE_SERVICE_ACCOUNT_B64}" \
      NODE_ENV=production \
      NEXT_PUBLIC_API_URL="${_API_URL}" \
      pnpm run build
  waitFor: ['Install Dependencies', 'Get Service Account']

# -------------------------------------------------------------------------
# 5. Deploy to Firebase App Hosting
# -------------------------------------------------------------------------
- id: 'Deploy'
  name: 'firebase/cli'
  args: 
    - 'deploy'
    - '--only'
    - 'apphosting'
    - '--project'
    - '${_FIREBASE_PROJECT_ID}'
  waitFor: ['Build']
  env:
    - 'FIREBASE_AUTH_EMULATOR_HOST='
    - 'GCLOUD_PROJECT=${_FIREBASE_PROJECT_ID}'
    - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/sa-key.json'

# -------------------------------------------------------------------------
# Substitutions
# -------------------------------------------------------------------------
substitutions:
  _FIREBASE_API_KEY: ''
  _FIREBASE_AUTH_DOMAIN: ''
  _FIREBASE_PROJECT_ID: 'ghost-money-world'
  _FIREBASE_STORAGE_BUCKET: ''
  _FIREBASE_MESSAGING_SENDER_ID: ''
  _FIREBASE_APP_ID: ''
  _FIREBASE_MEASUREMENT_ID: ''
  _API_URL: ''

# -------------------------------------------------------------------------
# Options
# -------------------------------------------------------------------------
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

